[package]
name = "siaod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
benchmarking = "0.4.12"
# heapsize = "0.4.2"
jemalloc-ctl = "0.5.4"
jemallocator = "0.5.4"
