[package]
name = "siaod_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
names = { version = "0.14.0", default-features = false }
colored = "2.0.4"
